name: Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
      
      - name: Test
        run: pnpm test
      
      - name: Build
        run: pnpm build
      
      - uses: actions/github-script@v7
        id: version_to_release
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            return 'v' + packageJson.version;

      - name: Publish to NPM
        run: |
          git tag ${{ steps.version_to_release.outputs.result }}
          git push origin ${{ steps.version_to_release.outputs.result }}
          pnpm -r publish --no-git-checks

      - name: GitHub Release
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 